import type { NextPage } from "next";
import { useState, useEffect } from "react";
import axios from "axios";

import Head from "next/head";
import { Box, Flex } from "@chakra-ui/layout";
import Navbar from "../components/Navbar";
import { Grid, Spinner } from "@chakra-ui/react";
import HomeCard from "../components/HomeCard";

const Home: NextPage = () => {
  const [pokemon, setPokemon] = useState<any>({});
  useEffect(() => {
    axios
      .get("https://pokeapi.co/api/v2/pokemon")
      .then((res) => {
        setPokemon(res.data);
      })
      .catch((err) => console.log(err));
  }, []);

  return (
    <div>
      <Head>
        <title>Gameshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box mt={10} mx="auto" boxSize="xl" width="80%">
        {!pokemon.results ? (
          <Flex justifyContent="center" alignItems="center">
            <Spinner color="telegram.600" size="xl" />
          </Flex>
        ) : (
          <Grid
            templateColumns={{
              xl: "repeat(5, 1fr)",
              sm: "repeat(3, 1fr)",
              lg: "repeat(4, 1fr)",
            }}
            gap={8}
          >
            {pokemon.results.map((item: any, index: number) => {
              return <HomeCard pokemon={item} key={index} />;
            })}
          </Grid>
        )}
      </Box>
    </div>
  );
};

export default Home;
